#!/bin/bash
#
# Simple script to export gw object data and sic-status. 
#
# Versions:
# - 2023052403 - Loop through >50 objects. 
#              - "Simplify" JQ query. 
# - 2023052402 - include missing CPMI objects
# - 2023052401 - Initial versions

OUTPUTDIR="`pwd`/gw_status"
ID="${OUTPUTDIR}/session.id"

if [ ! -x ${OUTPUTDIR} ]; then
        mkdir ${OUTPUTDIR}
fi

TOTAL=`mgmt_cli -r true -d 'System Data' show gateways-and-servers -f json | jq -r '.total'`


cd ${OUTPUTDIR}

echo "DOMAIN,GATEWAY OBJECT,IP ADDRESS,OBJECT TYPE,SIC STATUS" > gw_status.output

count=0

while [[ ${count} -lt ${TOTAL} ]];
do
  mgmt_cli -r true -d 'System Data' show gateways-and-servers details-level full -f json limit 50 offset $count| jq '.objects[]|select(.type == ("simple-gateway","CpmiGatewayCluster","CpmiVsClusterNetobj","cluster-member","CpmiVsxNetobj","C            pmiVsNetobj","CpmiVsxClusterMember","CpmiVsxClusterNetobj"))|[.domain.name,.name,."ipv4-address",.type,."sic-status"]|@csv' >> gw_status.output
  let "count = $count + 50"
done

echo "Script Complete"
echo "Output file: `pwd`/gw_status.output"
echo -ne "Data\n\n"
column -s, -t -o " " gw_status.output | tr '"' ' ' | tr '\\' ' ' | sed -e 's/^   //g'

